### PR TITLE
Expo SDK 33 - Change the dependency

### PR DESCRIPTION
**Pull request by YoshiYo**
Hi @Cretezy,

The new expo SDK 33 is released. 
I would like to do several changes on your package which don't need anymore the entire expo dependency. 
https://docs.expo.io/versions/latest/sdk/securestore/

What do you think about it ? 
Maybe it will be a major release.

### CODE REVIEW

**Comment by leviathan88** [comment]
@Cretezy will this be merged soon ?

**Comment by YoshiYo** [comment]
@leviathan88 
For the moment, you can use directly the fork in your package.json : 

`"redux-persist-expo-securestore": "https://github.com/YoshiYo/redux-persist-expo-securestore.git",`

If the merge is too long, I will publish a new repository to update this one. 
Tell me directly on my fork if there is a problem with this version. On my side, I don't have the expo warning anymore.

**Comment by leviathan88** [comment]
thanks @YoshiYo 
let's wait a little bit more and then check it out

**Comment by Cretezy** [comment]
Hi, sorry for the delay. Merging!

**Comment by Cretezy** [comment]
Just published `v2.0.0` with this!

**Pull request merged**
